/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainerProfileRouteImport } from './routes/trainer.profile'
import { Route as TrainerEarningsRouteImport } from './routes/trainer.earnings'
import { Route as TrainerDashboardRouteImport } from './routes/trainer.dashboard'
import { Route as TrainerClientsRouteImport } from './routes/trainer.clients'
import { Route as TrainerBookingsRouteImport } from './routes/trainer.bookings'
import { Route as TrainerAvailabilityRouteImport } from './routes/trainer.availability'
import { Route as AppWorkoutRouteImport } from './routes/_app.workout'
import { Route as AppTwinRouteImport } from './routes/_app.twin'
import { Route as AppTrainersRouteImport } from './routes/_app.trainers'
import { Route as AppScreeningRouteImport } from './routes/_app.screening'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPoseRouteImport } from './routes/_app.pose'
import { Route as AppNutritionRouteImport } from './routes/_app.nutrition'
import { Route as AppMatchesRouteImport } from './routes/_app.matches'
import { Route as AppDiscoverRouteImport } from './routes/_app.discover'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppBookingsRouteImport } from './routes/_app.bookings'
import { Route as AppAchievementsRouteImport } from './routes/_app.achievements'
import { Route as AppBookingsScheduleRouteImport } from './routes/_app.bookings.schedule'
import { Route as AppBookingsHistoryRouteImport } from './routes/_app.bookings.history'

const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerProfileRoute = TrainerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerEarningsRoute = TrainerEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerDashboardRoute = TrainerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerClientsRoute = TrainerClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerBookingsRoute = TrainerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerAvailabilityRoute = TrainerAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => TrainerRoute,
} as any)
const AppWorkoutRoute = AppWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => AppRoute,
} as any)
const AppTwinRoute = AppTwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainersRoute = AppTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => AppRoute,
} as any)
const AppScreeningRoute = AppScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPoseRoute = AppPoseRouteImport.update({
  id: '/pose',
  path: '/pose',
  getParentRoute: () => AppRoute,
} as any)
const AppNutritionRoute = AppNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsScheduleRoute = AppBookingsScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppBookingsRoute,
} as any)
const AppBookingsHistoryRoute = AppBookingsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppBookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/achievements': typeof AppAchievementsRoute
  '/bookings': typeof AppBookingsRouteWithChildren
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/discover': typeof AppDiscoverRoute
  '/matches': typeof AppMatchesRoute
  '/nutrition': typeof AppNutritionRoute
  '/pose': typeof AppPoseRoute
  '/profile': typeof AppProfileRoute
  '/screening': typeof AppScreeningRoute
  '/trainers': typeof AppTrainersRoute
  '/twin': typeof AppTwinRoute
  '/workout': typeof AppWorkoutRoute
  '/trainer/availability': typeof TrainerAvailabilityRoute
  '/trainer/bookings': typeof TrainerBookingsRoute
  '/trainer/clients': typeof TrainerClientsRoute
  '/trainer/dashboard': typeof TrainerDashboardRoute
  '/trainer/earnings': typeof TrainerEarningsRoute
  '/trainer/profile': typeof TrainerProfileRoute
  '/bookings/history': typeof AppBookingsHistoryRoute
  '/bookings/schedule': typeof AppBookingsScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/achievements': typeof AppAchievementsRoute
  '/bookings': typeof AppBookingsRouteWithChildren
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/discover': typeof AppDiscoverRoute
  '/matches': typeof AppMatchesRoute
  '/nutrition': typeof AppNutritionRoute
  '/pose': typeof AppPoseRoute
  '/profile': typeof AppProfileRoute
  '/screening': typeof AppScreeningRoute
  '/trainers': typeof AppTrainersRoute
  '/twin': typeof AppTwinRoute
  '/workout': typeof AppWorkoutRoute
  '/trainer/availability': typeof TrainerAvailabilityRoute
  '/trainer/bookings': typeof TrainerBookingsRoute
  '/trainer/clients': typeof TrainerClientsRoute
  '/trainer/dashboard': typeof TrainerDashboardRoute
  '/trainer/earnings': typeof TrainerEarningsRoute
  '/trainer/profile': typeof TrainerProfileRoute
  '/bookings/history': typeof AppBookingsHistoryRoute
  '/bookings/schedule': typeof AppBookingsScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/_app/achievements': typeof AppAchievementsRoute
  '/_app/bookings': typeof AppBookingsRouteWithChildren
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/matches': typeof AppMatchesRoute
  '/_app/nutrition': typeof AppNutritionRoute
  '/_app/pose': typeof AppPoseRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/screening': typeof AppScreeningRoute
  '/_app/trainers': typeof AppTrainersRoute
  '/_app/twin': typeof AppTwinRoute
  '/_app/workout': typeof AppWorkoutRoute
  '/trainer/availability': typeof TrainerAvailabilityRoute
  '/trainer/bookings': typeof TrainerBookingsRoute
  '/trainer/clients': typeof TrainerClientsRoute
  '/trainer/dashboard': typeof TrainerDashboardRoute
  '/trainer/earnings': typeof TrainerEarningsRoute
  '/trainer/profile': typeof TrainerProfileRoute
  '/_app/bookings/history': typeof AppBookingsHistoryRoute
  '/_app/bookings/schedule': typeof AppBookingsScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/trainer'
    | '/achievements'
    | '/bookings'
    | '/chat'
    | '/dashboard'
    | '/discover'
    | '/matches'
    | '/nutrition'
    | '/pose'
    | '/profile'
    | '/screening'
    | '/trainers'
    | '/twin'
    | '/workout'
    | '/trainer/availability'
    | '/trainer/bookings'
    | '/trainer/clients'
    | '/trainer/dashboard'
    | '/trainer/earnings'
    | '/trainer/profile'
    | '/bookings/history'
    | '/bookings/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/trainer'
    | '/achievements'
    | '/bookings'
    | '/chat'
    | '/dashboard'
    | '/discover'
    | '/matches'
    | '/nutrition'
    | '/pose'
    | '/profile'
    | '/screening'
    | '/trainers'
    | '/twin'
    | '/workout'
    | '/trainer/availability'
    | '/trainer/bookings'
    | '/trainer/clients'
    | '/trainer/dashboard'
    | '/trainer/earnings'
    | '/trainer/profile'
    | '/bookings/history'
    | '/bookings/schedule'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/trainer'
    | '/_app/achievements'
    | '/_app/bookings'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/discover'
    | '/_app/matches'
    | '/_app/nutrition'
    | '/_app/pose'
    | '/_app/profile'
    | '/_app/screening'
    | '/_app/trainers'
    | '/_app/twin'
    | '/_app/workout'
    | '/trainer/availability'
    | '/trainer/bookings'
    | '/trainer/clients'
    | '/trainer/dashboard'
    | '/trainer/earnings'
    | '/trainer/profile'
    | '/_app/bookings/history'
    | '/_app/bookings/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  TrainerRoute: typeof TrainerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/profile': {
      id: '/trainer/profile'
      path: '/profile'
      fullPath: '/trainer/profile'
      preLoaderRoute: typeof TrainerProfileRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/earnings': {
      id: '/trainer/earnings'
      path: '/earnings'
      fullPath: '/trainer/earnings'
      preLoaderRoute: typeof TrainerEarningsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/dashboard': {
      id: '/trainer/dashboard'
      path: '/dashboard'
      fullPath: '/trainer/dashboard'
      preLoaderRoute: typeof TrainerDashboardRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/clients': {
      id: '/trainer/clients'
      path: '/clients'
      fullPath: '/trainer/clients'
      preLoaderRoute: typeof TrainerClientsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/bookings': {
      id: '/trainer/bookings'
      path: '/bookings'
      fullPath: '/trainer/bookings'
      preLoaderRoute: typeof TrainerBookingsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/availability': {
      id: '/trainer/availability'
      path: '/availability'
      fullPath: '/trainer/availability'
      preLoaderRoute: typeof TrainerAvailabilityRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/_app/workout': {
      id: '/_app/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof AppWorkoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/twin': {
      id: '/_app/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof AppTwinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trainers': {
      id: '/_app/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof AppTrainersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/screening': {
      id: '/_app/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof AppScreeningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pose': {
      id: '/_app/pose'
      path: '/pose'
      fullPath: '/pose'
      preLoaderRoute: typeof AppPoseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nutrition': {
      id: '/_app/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AppNutritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matches': {
      id: '/_app/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings': {
      id: '/_app/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/achievements': {
      id: '/_app/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings/schedule': {
      id: '/_app/bookings/schedule'
      path: '/schedule'
      fullPath: '/bookings/schedule'
      preLoaderRoute: typeof AppBookingsScheduleRouteImport
      parentRoute: typeof AppBookingsRoute
    }
    '/_app/bookings/history': {
      id: '/_app/bookings/history'
      path: '/history'
      fullPath: '/bookings/history'
      preLoaderRoute: typeof AppBookingsHistoryRouteImport
      parentRoute: typeof AppBookingsRoute
    }
  }
}

interface AppBookingsRouteChildren {
  AppBookingsHistoryRoute: typeof AppBookingsHistoryRoute
  AppBookingsScheduleRoute: typeof AppBookingsScheduleRoute
}

const AppBookingsRouteChildren: AppBookingsRouteChildren = {
  AppBookingsHistoryRoute: AppBookingsHistoryRoute,
  AppBookingsScheduleRoute: AppBookingsScheduleRoute,
}

const AppBookingsRouteWithChildren = AppBookingsRoute._addFileChildren(
  AppBookingsRouteChildren,
)

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppBookingsRoute: typeof AppBookingsRouteWithChildren
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppMatchesRoute: typeof AppMatchesRoute
  AppNutritionRoute: typeof AppNutritionRoute
  AppPoseRoute: typeof AppPoseRoute
  AppProfileRoute: typeof AppProfileRoute
  AppScreeningRoute: typeof AppScreeningRoute
  AppTrainersRoute: typeof AppTrainersRoute
  AppTwinRoute: typeof AppTwinRoute
  AppWorkoutRoute: typeof AppWorkoutRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppBookingsRoute: AppBookingsRouteWithChildren,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppMatchesRoute: AppMatchesRoute,
  AppNutritionRoute: AppNutritionRoute,
  AppPoseRoute: AppPoseRoute,
  AppProfileRoute: AppProfileRoute,
  AppScreeningRoute: AppScreeningRoute,
  AppTrainersRoute: AppTrainersRoute,
  AppTwinRoute: AppTwinRoute,
  AppWorkoutRoute: AppWorkoutRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface TrainerRouteChildren {
  TrainerAvailabilityRoute: typeof TrainerAvailabilityRoute
  TrainerBookingsRoute: typeof TrainerBookingsRoute
  TrainerClientsRoute: typeof TrainerClientsRoute
  TrainerDashboardRoute: typeof TrainerDashboardRoute
  TrainerEarningsRoute: typeof TrainerEarningsRoute
  TrainerProfileRoute: typeof TrainerProfileRoute
}

const TrainerRouteChildren: TrainerRouteChildren = {
  TrainerAvailabilityRoute: TrainerAvailabilityRoute,
  TrainerBookingsRoute: TrainerBookingsRoute,
  TrainerClientsRoute: TrainerClientsRoute,
  TrainerDashboardRoute: TrainerDashboardRoute,
  TrainerEarningsRoute: TrainerEarningsRoute,
  TrainerProfileRoute: TrainerProfileRoute,
}

const TrainerRouteWithChildren =
  TrainerRoute._addFileChildren(TrainerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  TrainerRoute: TrainerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
