/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkoutRouteImport } from './routes/_app.workout'
import { Route as AppTwinRouteImport } from './routes/_app.twin'
import { Route as AppTrainersRouteImport } from './routes/_app.trainers'
import { Route as AppScreeningRouteImport } from './routes/_app.screening'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPoseRouteImport } from './routes/_app.pose'
import { Route as AppNutritionRouteImport } from './routes/_app.nutrition'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAchievementsRouteImport } from './routes/_app.achievements'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkoutRoute = AppWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => AppRoute,
} as any)
const AppTwinRoute = AppTwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainersRoute = AppTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => AppRoute,
} as any)
const AppScreeningRoute = AppScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPoseRoute = AppPoseRouteImport.update({
  id: '/pose',
  path: '/pose',
  getParentRoute: () => AppRoute,
} as any)
const AppNutritionRoute = AppNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/achievements': typeof AppAchievementsRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/nutrition': typeof AppNutritionRoute
  '/pose': typeof AppPoseRoute
  '/profile': typeof AppProfileRoute
  '/screening': typeof AppScreeningRoute
  '/trainers': typeof AppTrainersRoute
  '/twin': typeof AppTwinRoute
  '/workout': typeof AppWorkoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/achievements': typeof AppAchievementsRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/nutrition': typeof AppNutritionRoute
  '/pose': typeof AppPoseRoute
  '/profile': typeof AppProfileRoute
  '/screening': typeof AppScreeningRoute
  '/trainers': typeof AppTrainersRoute
  '/twin': typeof AppTwinRoute
  '/workout': typeof AppWorkoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/achievements': typeof AppAchievementsRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/nutrition': typeof AppNutritionRoute
  '/_app/pose': typeof AppPoseRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/screening': typeof AppScreeningRoute
  '/_app/trainers': typeof AppTrainersRoute
  '/_app/twin': typeof AppTwinRoute
  '/_app/workout': typeof AppWorkoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/achievements'
    | '/chat'
    | '/dashboard'
    | '/nutrition'
    | '/pose'
    | '/profile'
    | '/screening'
    | '/trainers'
    | '/twin'
    | '/workout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/achievements'
    | '/chat'
    | '/dashboard'
    | '/nutrition'
    | '/pose'
    | '/profile'
    | '/screening'
    | '/trainers'
    | '/twin'
    | '/workout'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/achievements'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/nutrition'
    | '/_app/pose'
    | '/_app/profile'
    | '/_app/screening'
    | '/_app/trainers'
    | '/_app/twin'
    | '/_app/workout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workout': {
      id: '/_app/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof AppWorkoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/twin': {
      id: '/_app/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof AppTwinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trainers': {
      id: '/_app/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof AppTrainersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/screening': {
      id: '/_app/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof AppScreeningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pose': {
      id: '/_app/pose'
      path: '/pose'
      fullPath: '/pose'
      preLoaderRoute: typeof AppPoseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nutrition': {
      id: '/_app/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AppNutritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/achievements': {
      id: '/_app/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNutritionRoute: typeof AppNutritionRoute
  AppPoseRoute: typeof AppPoseRoute
  AppProfileRoute: typeof AppProfileRoute
  AppScreeningRoute: typeof AppScreeningRoute
  AppTrainersRoute: typeof AppTrainersRoute
  AppTwinRoute: typeof AppTwinRoute
  AppWorkoutRoute: typeof AppWorkoutRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNutritionRoute: AppNutritionRoute,
  AppPoseRoute: AppPoseRoute,
  AppProfileRoute: AppProfileRoute,
  AppScreeningRoute: AppScreeningRoute,
  AppTrainersRoute: AppTrainersRoute,
  AppTwinRoute: AppTwinRoute,
  AppWorkoutRoute: AppWorkoutRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
